apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-manager-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-manager-center
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: app-manager-center
          image: rgs.hlxd.com:8081/cloud-service/app-manager-center:latest
          env:
            - name: AUTHOR
              value: app-manager-center
          ports:
            - containerPort: 30016
          volumeMounts:
            - name: ftl
              mountPath: /tools/jar_image
      volumes:
        - name: ftl
          hostPath:
            path: /tools/jar_image
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: app-managre-center
spec:
  ports:
    - port: 30016
      protocol: TCP
      targetPort: 30016
      nodePort: 30016
  type: NodePort
  selector:
    app: app-manager-center
