apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: zipkin-server
          image: rgs.hlxd.com:8081/cloud-service/zipkin-server:latest
          env:
            - name: AUTHOR
              value: zipkin-server
          ports:
            - containerPort: 30411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
spec:
  ports:
    - port: 30411
      protocol: TCP
      targetPort: 30411
      nodePort: 30411
  type: NodePort
  selector:
    app: zipkin-server
