apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: register-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: register-center
    spec:
      containers:
        - name: register-center
          image: rgs.hlxd.com:8081/cloud-service/register-center:latest
          env:
            - name: AUTHOR
              value: register-center
          ports:
            - containerPort: 30020
---
apiVersion: v1
kind: Service
metadata:
  name: register-center
spec:
  ports:
    - port: 30020
      protocol: TCP
      targetPort: 30020
      nodePort: 30020
  type: NodePort
  selector:
    app: register-center
