apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: log-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: log-center
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: log-center
          image: rgs.hlxd.com:8081/cloud-service/log-center:latest
          env:
            - name: AUTHOR
              value: log-center
          ports:
            - containerPort: 30023
---
apiVersion: v1
kind: Service
metadata:
  name: log-center
spec:
  ports:
    - port: 30023
      protocol: TCP
      targetPort: 30023
      nodePort: 30023
  type: NodePort
  selector:
    app: log-center
