apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-zuul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-zuul
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: gateway-zuul
          image: rgs.hlxd.com:8081/cloud-service/gateway-zuul:latest
          env:
            - name: AUTHOR
              value: gateway-zuul
          ports:
            - containerPort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-zuul
spec:
  ports:
    - port: 30080
      protocol: TCP
      targetPort: 30080
      nodePort: 30080
  type: NodePort
  selector:
    app: gateway-zuul
