apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tx-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tx-manager
    spec:
      containers:
        - name: tx-manager
          image: rgs.hlxd.com:8081/cloud-service/tx-manager:latest
          env:
            - name: AUTHOR
              value: tx-manager
          ports:
            - containerPort: 30026
---
apiVersion: v1
kind: Service
metadata:
  name: tx-manager
spec:
  ports:
    - port: 30026
      protocol: TCP
      targetPort: 30026
      nodePort: 30026
  type: NodePort
  selector:
    app: tx-manager
