apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: file-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: file-center
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: file-center
          image: rgs.hlxd.com:8081/cloud-service/file-center:latest
          env:
            - name: AUTHOR
              value: file-center
          ports:
            - containerPort: 30024
---
apiVersion: v1
kind: Service
metadata:
  name: file-center
spec:
  ports:
    - port: 30024
      protocol: TCP
      targetPort: 30024
      nodePort: 30024
  type: NodePort
  selector:
    app: flie-center
