spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3305/cloud_service?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Hlxd@123456
  rabbitmq:
    host: local.rabbitmq.com
    port: 5672
    username: cloud-dev
    password: cloud-dev
    virtual-host: /
  redis:
    host: local.redis.com
    port: 6379
    database: 1
  mvc:
    servlet:
      load-on-startup: 1
mybatis:
  type-aliases-package: com.cloud.model.gateway
  mapper-locations: classpath:/mybatis-mappers/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
zuul:
  ignored-services: '*'
  sensitiveHeaders:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
cron:
  black-ip: 0 0/5 * * * ?
logging:
  level:
    root: warn
    com.cloud: warn