apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitor-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor-center
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: monitor-center
          image: rgs.hlxd.com:8081/cloud-service/monitor-center:latest
          env:
            - name: AUTHOR
              value: monitor-center
          ports:
            - containerPort: 30901
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-center
spec:
  ports:
    - port: 30901
      protocol: TCP
      targetPort: 30901
      nodePort: 30901
  type: NodePort
  selector:
    app: monitor-center
