spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3305/cloud_appmanage?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Hlxd@123456
  rabbitmq:
    host: local.rabbitmq.com
    port: 5672
    username: cloud-dev
    password: cloud-dev
    virtual-host: /
  redis:
    host: local.redis.com
    port: 6379
gitlab:
  apiPrefix: http://10.190.19.244:8889
  private-token: z1zfZqGHRZ3JxWvKzSS1
  domain: gitlab.hlxd.com
  ip: 10.190.19.244
wxcp:
  apiPrefix: http://10.130.86.65
logging:
  level:
    root: warn
    com.cloud: warn