spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3305/cloud_service?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Hlxd@123456
  rabbitmq:
    host: local.rabbitmq.com
    port: 5672
    username: cloud-dev
    password: cloud-dev
    virtual-host: /
  redis:
    host: local.redis.com
    port: 6379
jenkins:
  jenUrl: http://10.190.19.244:8888/
  username: admin
  passwordorToken: admin
#上传文件地址
web:
  createFileApi: http://10.190.19.244:8091/createFile
  deleteServiceApi: http://10.190.19.244:8091/delete
logging:
  level:
    root: warn
    com.cloud: warn