apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-center
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: user-center
          image: rgs.hlxd.com:8081/cloud-service/user-center:latest
          env:
            - name: AUTHOR
              value: user-center
          ports:
            - containerPort: 30012
---
apiVersion: v1
kind: Service
metadata:
  name: user-center
spec:
  ports:
    - port: 30012
      protocol: TCP
      targetPort: 30012
      nodePort: 30012
  type: NodePort
  selector:
    app: user-center
