apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platform-user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: platform-user
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: platform-user
          image: rgs.hlxd.com:8081/cloud-service/platform-user:latest
          env:
            - name: AUTHOR
              value: platform-user
          ports:
            - containerPort: 30031
---
apiVersion: v1
kind: Service
metadata:
  name: platform-user
spec:
  ports:
    - port: 30031
      protocol: TCP
      targetPort: 30031
      nodePort: 30031
  type: NodePort
  selector:
    app: platform-user
