apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth-center
    spec:
      hostAliases:
        - ip: "192.168.11.162"
          hostnames:
            - "local.redis.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.rabbitmq.com"
        - ip: "192.168.11.162"
          hostnames:
            - "local.mysql.com"
      containers:
        - name: oauth-center
          image: rgs.hlxd.com:8081/cloud-service/oauth-center:latest
          env:
            - name: AUTHOR
              value: oauth-center
          ports:
            - containerPort: 30013
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-center
spec:
  ports:
    - port: 30013
      protocol: TCP
      targetPort: 30013
      nodePort: 30013
  type: NodePort
  selector:
    app: oauth-center
